
function(fetch_svd MCU)
    if(NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/_deps/SVD/Contents.txt)
        file(DOWNLOAD https://raw.githubusercontent.com/posborne/cmsis-svd/master/data/STMicro/Contents.txt ${CMAKE_CURRENT_SOURCE_DIR}/_deps/SVD/Contents.txt)
    endif()
    if(NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/_deps/SVD/Contents.txt)
        message(FATAL_ERROR "Could not download repository contents")
    endif()
    file(STRINGS ${CMAKE_CURRENT_SOURCE_DIR}/_deps/SVD/Contents.txt SVD_REPO_CONTENTS)

    foreach(SVD_GROUP ${SVD_REPO_CONTENTS})
        string(FIND ${SVD_GROUP} ${MCU} MCU_FOUND)
        if(MCU_FOUND GREATER -1)
            string(REGEX MATCH "STM32[a-zA-Z0-9]*.svd" SVD_FILE_NAME ${SVD_GROUP})
            break()
        endif()
    endforeach()
    if(NOT SVD_FILE_NAME)
        message(FATAL_ERROR "Could not find .svd file in remote repository for ${MCU}")
    endif()

    if(NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/_deps/SVD/${SVD_FILE_NAME})
        file(DOWNLOAD https://raw.githubusercontent.com/posborne/cmsis-svd/master/data/STMicro/${SVD_FILE_NAME} ${CMAKE_CURRENT_SOURCE_DIR}/_deps/SVD/${SVD_FILE_NAME})
    endif()
    if(NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/_deps/SVD/${SVD_FILE_NAME})
        message(FATAL_ERROR "Could not download .svd file")
    endif()
    set(PENV{SVD_FILE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/_deps/SVD/${SVD_FILE_NAME})
endfunction()